"""ChangeMesh Core Module.

Contains core components including the canonical BoundedGeminiClient
and Gemini Structured Output validation & parsing contracts.
"""

from src.core.gemini_client import (
    CANONICAL_API_VERSION,
    CANONICAL_LOCATION,
    CANONICAL_MODEL_ID,
    CANONICAL_PROVIDER,
    CANONICAL_SAFETY_POLICY,
    DEFAULT_BACKOFF_MULTIPLIER,
    DEFAULT_INITIAL_RETRY_DELAY_SECONDS,
    DEFAULT_MAX_ATTEMPTS,
    DEFAULT_MAX_OUTPUT_TOKENS,
    DEFAULT_MAX_RETRY_DELAY_SECONDS,
    DEFAULT_PROJECT_ID,
    DEFAULT_TIMEOUT_SECONDS,
    MAX_ATTEMPTS_CEILING,
    MAX_TIMEOUT_SECONDS,
    MAX_TOKEN_CEILING,
    MIN_ATTEMPTS_FLOOR,
    MIN_TIMEOUT_SECONDS,
    MIN_TOKEN_FLOOR,
    RETRYABLE_STATUS_CODES,
    SDK_RETRY_ATTEMPTS_DISABLED,
    BoundedGeminiClient,
    CanonicalSafetyPolicyItem,
    ModelAPIError,
    ModelCallTelemetry,
    ModelClientError,
    ModelConfigurationError,
    ModelEmptyResponseError,
    ModelInitializationError,
    ModelResponse,
    ModelRetryExhaustedError,
    ModelSafetyBlockedError,
    ModelTimeoutError,
    get_canonical_safety_settings,
    sanitize_telemetry_call_id,
)
from src.core.gemini_structured_output import (
    CANONICAL_ACTION_TYPES,
    CANONICAL_AUTHORITY_LANE,
    CANONICAL_SPECIALIST_ROLES,
    CANONICAL_STRUCTURED_SCHEMA_VERSION,
    GoalDecompositionResult,
    GoalDecompositionSubGoal,
    PolicyComplianceStatus,
    PolicyExplanationResult,
    PolicyImpactLevel,
    PolicyRuleExplanation,
    SemanticAssessmentVerdict,
    SemanticAuditResult,
    SemanticClaimAssessment,
    SemanticEvidenceCitation,
    SemanticRiskLevel,
    StructuredOutputError,
    StructuredOutputJSONError,
    StructuredOutputSecurityError,
    StructuredOutputValidationError,
    build_goal_decomposition_prompt,
    build_policy_explanation_prompt,
    build_semantic_audit_prompt,
    parse_goal_decomposition_output,
    parse_policy_explanation_output,
    parse_semantic_audit_output,
    parse_structured_json,
    validate_action_type,
    validate_safe_endpoint,
    validate_safe_relative_path,
)

__all__ = [
    # Canonical Client
    "BoundedGeminiClient",
    # Constants & Bounds
    "CANONICAL_MODEL_ID",
    "CANONICAL_API_VERSION",
    "CANONICAL_PROVIDER",
    "CANONICAL_LOCATION",
    "DEFAULT_PROJECT_ID",
    "SDK_RETRY_ATTEMPTS_DISABLED",
    "DEFAULT_TIMEOUT_SECONDS",
    "MIN_TIMEOUT_SECONDS",
    "MAX_TIMEOUT_SECONDS",
    "DEFAULT_MAX_OUTPUT_TOKENS",
    "MIN_TOKEN_FLOOR",
    "MAX_TOKEN_CEILING",
    "DEFAULT_MAX_ATTEMPTS",
    "MAX_ATTEMPTS_CEILING",
    "MIN_ATTEMPTS_FLOOR",
    "DEFAULT_INITIAL_RETRY_DELAY_SECONDS",
    "DEFAULT_BACKOFF_MULTIPLIER",
    "DEFAULT_MAX_RETRY_DELAY_SECONDS",
    "RETRYABLE_STATUS_CODES",
    "CANONICAL_SAFETY_POLICY",
    "CanonicalSafetyPolicyItem",
    "get_canonical_safety_settings",
    "sanitize_telemetry_call_id",
    # Telemetry & Response Models
    "ModelCallTelemetry",
    "ModelResponse",
    # Model Exceptions
    "ModelClientError",
    "ModelConfigurationError",
    "ModelInitializationError",
    "ModelTimeoutError",
    "ModelRetryExhaustedError",
    "ModelAPIError",
    "ModelSafetyBlockedError",
    "ModelEmptyResponseError",
    # Structured Output Constants & Enums
    "CANONICAL_AUTHORITY_LANE",
    "CANONICAL_STRUCTURED_SCHEMA_VERSION",
    "CANONICAL_ACTION_TYPES",
    "CANONICAL_SPECIALIST_ROLES",
    "SemanticAssessmentVerdict",
    "SemanticRiskLevel",
    "PolicyImpactLevel",
    "PolicyComplianceStatus",
    # Structured Output Models
    "GoalDecompositionSubGoal",
    "GoalDecompositionResult",
    "PolicyRuleExplanation",
    "PolicyExplanationResult",
    "SemanticEvidenceCitation",
    "SemanticClaimAssessment",
    "SemanticAuditResult",
    # Structured Output Exceptions
    "StructuredOutputError",
    "StructuredOutputJSONError",
    "StructuredOutputValidationError",
    "StructuredOutputSecurityError",
    # Structured Output Validation & Parsers
    "validate_safe_relative_path",
    "validate_safe_endpoint",
    "validate_action_type",
    "parse_structured_json",
    "parse_goal_decomposition_output",
    "parse_policy_explanation_output",
    "parse_semantic_audit_output",
    "build_goal_decomposition_prompt",
    "build_policy_explanation_prompt",
    "build_semantic_audit_prompt",
]
